name: linting, testing, building

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2

      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: npm install

      - name: build production project
        run: npm run build:prod

      - name: linting typescript
        run: npm run lint:ts

      - name: linting scss
        run: npm run lint:scss

      - name: unit testing
        run: npm run test:unit

      - name: build storybook
        run: |
          npm run storybook:build &> storybook.log &
          echo $! > storybook_pid.txt
        env:
          CI: true

      - name: Wait for Storybook to start
        run: sleep 180 # Подождите 180 секунд, при необходимости измените

      - name: Check if Storybook is running
        run: |
          for i in {1..10}; do
            if curl -s http://127.0.0.1:6006 &> /dev/null; then
              echo "Storybook is up!"
              break
            else
              echo "Waiting for Storybook..."
              sleep 10
            fi
          done

      - name: Show Storybook Log
        run: cat storybook.log

      - name: Run visual tests
        run: npx loki test --host 127.0.0.1 --port 6006

      - name: Kill Storybook process
        if: always()
        run: kill $(cat storybook_pid.txt)
