name: linting, testing, building

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2

      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: npm install

      - name: build production project
        run: npm run build:prod

      - name: linting typescript
        run: npm run lint:ts

      - name: linting scss
        run: npm run lint:scss

      - name: unit testing
        run: npm run test:unit

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Build and run Storybook in Docker
        run: |
          docker build -t storybook-container -f config/storybook/Dockerfile .
          docker run -d -p 6006:6006 -v ${{ github.workspace }}/.loki:/app/.loki --name storybook-container storybook-container
          sleep 10 # wait for Storybook to start

      - name: Run visual tests
        run: npx loki test --host 127.0.0.1 --port 6006

      - name: Stop and remove Storybook container
        if: always()
        run: |
          docker stop storybook-container
          docker rm storybook-container